### ISSUE TITLE
Proxy-statistics show stats for deleted namespaces

### ISSUE THREAD

**Issue by jtorreke** [openvstorage/alba#200]
An example will clarify. The list of namespaces in the proxy-statistics:

```
In [3]: for ns in AlbaCLI.run('proxy-statistics -h 127.0.0.1 -p 26203', as_json=True)['ns_stats']:
   ...:     print ns[0]
   ...:     
9a7a0689-8559-4182-a46f-5788a04d73a4
fd-be-vpool-16583a8c-b488-4189-915c-74134753d049
27f4e45d-0ef8-4b00-8297-6e0e8532c008
```

The list of namespaces:

```
In [7]: for space in AlbaCLI.run('list-namespaces --config etcd://127.0.0.1:2379/ovs/arakoon/be-backend-abm/config', as_json=True):
   ...:     print space['name']
   ...:     
9a7a0689-8559-4182-a46f-5788a04d73a4
fd-be-vpool-16583a8c-b488-4189-915c-74134753d049
```

Am I missing something or checking this in the wrong way? It might as well be me.

**Comment by domsj** [comment]
I don't think you're checking it the wrong way. In a way this behaviour is 'by design', or at least I could explain it as such after the facts ;-).
This allows you to get the latest statistics of a namespace you just deleted, otherwise this info would be lost.
We could clear this from the statistics if the namespace is deleted by this (the same) proxy ... but I don't think we want to do this. Because 1) we throw away info someone may still want and 2) we can't throw it away if the namespace is deleted by another proxy, or from the cli.
If this info about deleted namespaces bothers you we could add a call to clear only this part of the statistics?

**Comment by wimpers** [comment]
@domsj are these statistics kept for ever or is there an option to force the deletion of statistics?

**Comment by domsj** [comment]
There is already an option to clear all statistics when fetching them.
I'm not quite following with the 'multi-authenticated rename' thingie you're mentioning...

**Comment by wimpers** [comment]
Authenticated rename should be autheticated delete.

@domsj  as discussed, please add a call so the statistics can be deleted for a specific volume. 

@jtorreke, currently minor, if you would disagree please leave a comment below!

**Comment by jtorreke** [comment]
I agree on the minor priority and we can work around it. It would just be silly to keep stats forever and ever about something which happened ages ago.
