### ISSUE TITLE
Namespace names in OSD backend or Cache backend are not UTF-8

### ISSUE THREAD

**Issue by khenderick** [openvstorage/alba#260]
Namespace names in OSD backend or Cache backend are not UTF-8. While not strictly required, UTF-8 is advised for JSON, and the python json parser seems to depend on this advise as it can't parse the JSON output returned by e.g. show-namespaces.

It would be nice if the counter could be added in some more readable way, e.g. `<prefix>_<counter>` where counter is `00000001`, `00000002`, and so on.

**Comment by toolslive** [comment]
Does this mean that Alba should have a constraint on the names of namespaces ?
#262 changes the generated filenames, but what about names decided by users?

**Comment by domsj** [comment]
If we were to have a constraint on the names of namespaces then it should probably be optional, as otherwise it's a breaking change. (New setups could optionally enable this constraint.)
The main reason I wanted to tackle this issue is that I don't want to have a hard time when using the cli to query info about these generated namespaces...
I'll leave the issue open for now so we can still decide later on what we want to do with this

**Comment by khenderick** [comment]
As @toolslive pointed out, ```UTF-8```, ```UTF-16``` or ```UTF-32``` is required, and ```UTF-8``` is the recommended option of these 3. See https://tools.ietf.org/html/rfc7159#section-8.1

**Comment by wimpers** [comment]
Moved to Gilbert as non SRP.

**Comment by wimpers** [comment]
Closing this issue as we protect against this when creating our own namespaces. if someone creates a namespace he is responsible for having a name he can parse later on.
