### ISSUE TITLE
Replication: local read preference

### ISSUE THREAD

**Issue by wimpers** [openvstorage/alba#301]
In case you configure the policy of a global backend to be X-way replication, we should always try to read from a local backend instead of going to another datacenter. Currently this isn't build in so it could be that for a read you access another datacenter while there is a copy in the local datacenter.

Question:
- How does a proxy know which is the local backend?

**Comment by domsj** [comment]
Regarding the question: I think the proxy should have a configuration option that tells it which osd(s) it should prefer to read from

**Comment by wimpers** [comment]
Could we use the domains tag for that?

**Comment by domsj** [comment]
Alba doesn't know about domain tags. But the framework might be able to configure the alba proxy correctly (regarding the local read preference) based on these domain tags (@khenderick)?

**Comment by domsj** [comment]
Just a clarification so that I can close #389: this should be done for full object reads and partial reads.
This probably isn't needed for the rora reads. Rora reads only make sense when the rora path reads from an alba (wether that is the main one, or a fragment cache in front of it) that is fully in the same datacenter.

**Comment by wimpers** [comment]
Only required for global backends.

**Comment by toolslive** [comment]
#457
