### ISSUE TITLE
Manifest cache does not get properly refreshed after maintenance agent action

### ISSUE THREAD

**Issue by pploegaert** [openvstorage/alba#371]
Observed during rora performance testing
@domsj: pls update with more clear description - thx

**Comment by domsj** [comment]
Slightly longer explanation:
A proxy holds on to outdated manifests for too long after a maintenance agent moves fragments.
The proxy will only refresh the manifest when so many fragments have been moved that it can no longer rebuild the object from the fragments that are still reachable.
This results in degraded performance, because the proxy (and rora) can no longer do partial reads.
The proxy should refresh the manifest as soon as it detects a missing fragment.
